### ISSUE TITLE
Report error button only appears on the first page

### ISSUE THREAD

**Issue by JMante1** [SynBioHub/synbiohub.github.io#4]
It would be very nice to have it appear in the bar on the left or right of every page.

**Comment by PRUBHTEJ** [comment]
That can be done.
I'll try to include this in the next week's taks.

**Comment by cjmyers** [comment]
Create a new section called "Report an Issue".  This section should include the following information:

1) If you are a SynBioHub developer with a question about SynBioHub or plugin development, please join the synbiohub-dev (https://groups.google.com/u/1/g/synbiohub-dev) mailing list and post your question there.

2) If you are a SynBioHub user with a question about how to use SynBioHub, please join the synbiohub-users (https://groups.google.com/u/1/g/synbiohub-users) mailing list and post your question there.

3) If you have found an error in this user documentation, please log your issue here (https://github.com/SynBioHub/synbiohub.github.io/issues).

4) If you have found an error in the API documentation, please log your issue here (https://github.com/SynBioHub/api-docs).

5) If you have found an error in SynBioHub itself, please log your issue here (https://github.com/SynBioHub/synbiohub).

6) If you have a suggestion for a new SynBioHub plugin, please make your suggestion here (https://github.com/SynBioHub/synbiohub-plugins).

7) If you have found a problem in an existing SynBioHub plugin, please log your issue in the appropriate issue tracker for the plugin found in the table(link to the table).

**Comment by PRUBHTEJ** [comment]
As of now, I've removed the error button from the first page. I'm waiting for a reply on the idea of childpages, if that shall suffice.

**Comment by JMante1** [comment]
I think the child pages under report an error would be "reporting an error" and "questions and contact".

### Reporting an Error
If you want to report an error please see the respective pages. Note that for enhancements there are contact details in the "questions and contact" section.

- This documentation: https://github.com/SynBioHub/synbiohub.github.io/issues
- API documentation: https://github.com/SynBioHub/api-docs
- Synbiohub itself: https://github.com/SynBioHub/synbiohub
- Synbiohub plugins: please log your issue in the appropriate issue tracker for the plugin found in the table(link to the table)

### Questions and Contact

If you are a *SynBioHub developer* with a question about SynBioHub or plugin development, please join the synbiohub-dev (https://groups.google.com/u/1/g/synbiohub-dev) mailing list and post your question there.

If you are a *SynBioHub user* with a question about how to use SynBioHub, please join the synbiohub-users (https://groups.google.com/u/1/g/synbiohub-users) mailing list and post your question there.

If you have a suggestion for a new *SynBioHub plugin*, please make your suggestion here (https://github.com/SynBioHub/synbiohub-plugins).

**Comment by PRUBHTEJ** [comment]
Ohkay!

**Comment by PRUBHTEJ** [comment]
I have added both the child pages for this section but there needs to be an opening line as well, specifically, for this section. What could that possibly be?

**Comment by JMante1** [comment]
I would add the opening line: "We appreciate any feedback or suggested improvements you have. If you have an error please see reporting an error. If you would like help with something or to discuss a potential feature please see the mailing lists."

**Comment by PRUBHTEJ** [comment]
Done that. Kindly have a look.
